name: Build OpenWRT package (test)

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt version to test'
        required: true
        default: '24.10'
        type: choice
        options:
        - '24.10'
        - '25.12'
      verbose:
        description: 'Verbose build output'
        required: false
        default: false
        type: boolean

# Minimize GITHUB_TOKEN permissions for security
permissions: {}

jobs:
  build-test:
    strategy:
      matrix:
        include:
          # 24.10
          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'x86_64'

          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.3'
          #   arch: 'aarch64_cortex-a53'

          - openwrt_version: '25.12'
            openwrt_build_version: '25.12.0-rc4'
            arch: 'aarch64_cortex-a53'

          - openwrt_version: '24.10'
            openwrt_build_version: '24.10.5'
            arch: 'aarch64_cortex-a53'

          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'aarch64_cortex-a72'

          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'arm_cortex-a7_neon-vfpv4'

          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'arm_cortex-a9'

          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'mediatek-filogic'
          #   target: 'mediatek/filogic'
          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'bcm27xx-bcm2711'
          #   target: 'bcm27xx/bcm2711'

          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'mips_24kc'
          # - openwrt_version: '24.10'
          #   openwrt_build_version: '24.10.4'
          #   arch: 'mipsel_24kc'
      fail-fast: false

    uses: Zerogiven/gh-openwrt-package-build-workflows/.github/workflows/reusable-build.yml@prometheus-node-exporter-lua-patch
    with:
      package_name: 'quectel-rm520n-thermal'
      sdk_packages: 'quectel-rm520n-thermal'
      artifacts_patterns: |
        kmod-quectel-rm520n-thermal*.ipk
        quectel-rm520n-thermal*.ipk
        prometheus-node-exporter-lua-*quectel-rm520n-thermal*.ipk
      openwrt_version: ${{ matrix.openwrt_version }}
      openwrt_build_version: ${{ matrix.openwrt_build_version }}
      arch: ${{ matrix.arch }}
      target: ${{ matrix.target }}
      selected_version: ${{ github.event.inputs.openwrt_version }}
      verbose: ${{ github.event.inputs.verbose == 'true' }}
      free_disk_space: false
